package io.bullseye.common;

public enum MetricType {
    HOST_CPU_USAGE,
    HOST_MEMORY_USAGE,
    HOST_LOAD_AVERAGE,
    PROCESS_CPU_USAGE,
    PROCESS_MEMORY_USAGE,
    JVM_HEAP_USAGE,
    JVM_GC_PAUSE,
    THREAD_POOL_USAGE,
    DB_POOL_USAGE,
    DB_POOL_PENDING,
    REQUEST_QUEUE_DEPTH,
    HTTP_ERROR_RATE,
    HTTP_P95_LATENCY,
    HTTP_P99_LATENCY
}
